### ISSUE TITLE
Validate flight name

### ISSUE THREAD

**Issue by nguyenhuuhoanggiang** [hoadinh2010/Vietexpress#101]
- [x] Flight name must not be contained special character such as #
- [x] Only use # when displaying, not creating or editing

**Comment by NguyenMinhh** [comment]
Already fixed at below route:
- /check-tracking : TrackingCheckablePage.jsx
- /create-tracking : TrackingCreationPage.jsx
- /flights : FlightsPage.jsx
- /search : SearchResult.jsx
- Create flight modal: FlightsForm.jsx
- Flight detail modal: FlightDetailFlightDetail.jsx
