### ISSUE TITLE
Change flight status to 'Checking' after scanning first tracking number

### ISSUE THREAD

**Issue by nguyenhuuhoanggiang** [hoadinh2010/Vietexpress#102]
- [x] Flight status must be changed to 'Đang kiểm tra' once any tracking of this flight was scanned.

**Comment by hoadinh2010** [comment]
@nguyenhuuhoanggiang , @NguyenMinhh The status of the flight will be changed to `Checking` when user click on the `Kiểm tra` button on the list flight. This have already been implemented. Check it again, plz!
