### ISSUE TITLE
Create internal label

### ISSUE THREAD

**Issue by nguyenhuuhoanggiang** [hoadinh2010/Vietexpress#135]
![Customer](https://user-images.githubusercontent.com/38091121/55161300-c47dc880-5197-11e9-9787-b24e3b7501cc.jpg)
![Guest](https://user-images.githubusercontent.com/38091121/55161302-c47dc880-5197-11e9-805c-e15a0a0c70d9.jpg)

**Comment by anhmht** [comment]
![screencapture-localhost-3000-create-internal-label-2019-03-30-17_56_10](https://user-images.githubusercontent.com/38060950/55275351-890a0800-5317-11e9-8d40-75c95ffccd13.png)
