### ISSUE TITLE
Print PDF with the created internal barcode 

### ISSUE THREAD

**Issue by hoadinh2010** [hoadinh2010/Vietexpress#150]
- [x] After creating a `Qua Bieu`, we will print a PDF file. Discuss with @anhmht to know more about the layout of the pdf file. The main idea: Barcode is generated by a package (@anhmht did this feature). You will show this generated barcode in a hidden html and print this html.

**Comment by nguyenhuuhoanggiang** [comment]
<img width="624" alt="Screen Shot 2019-04-06 at 6 23 48 PM" src="https://user-images.githubusercontent.com/38091121/55670030-3bf2dc80-58a9-11e9-97d0-78532abfba6d.png">
<img width="1238" alt="Screen Shot 2019-04-06 at 6 24 29 PM" src="https://user-images.githubusercontent.com/38091121/55670031-3bf2dc80-58a9-11e9-94c4-6893a9eccedf.png">
