### ISSUE TITLE
Init basic Customer Creation Form

### ISSUE THREAD

**Issue by hoadinh2010** [hoadinh2010/Vietexpress#2]
- Using Ant design to create the customer creation form based on the login form
- Ask Giang for the mandatory or optional field

**Comment by hoadinh2010** [comment]
Basic Form: 
```UserId (VXxxx)
Name:
Email: 
PhoneNumb: allow 2 phone numbers
VNAddress: allow 2 address (1 primary, 1 secondary)
Service: (Door to door, pickup)
PaymentMethod: (Pay in Vietnam)```

**Comment by anhmht** [comment]
![screencapture-localhost-3000-register-2019-03-03-11_27_50](https://user-images.githubusercontent.com/38060950/53691066-3fc2a900-3da9-11e9-8d2e-dfabcda45145.png)
