### ISSUE TITLE
Some enhancements 

### ISSUE THREAD

**Issue by hoadinh2010** [hoadinh2010/Vietexpress#54]
- [x] Need to validate the search input before searching. 
 - [x] Increase the width of the customer creation form and change the label of form input to make form prettier
 - [x] Something went wrong when search tracking 
![image](https://user-images.githubusercontent.com/48083610/54522711-72bb8e00-49a0-11e9-9100-ae13358bd49d.png)

**Comment by hoadinh2010** [comment]
The bug happened because this line 
`    const customer = new CustomerWorker(tracking.userId);`
The userId of a tracking is unique ID of customer, it not a unique Id, you should update the constructor, if it can't find data by the Id, using unique ID of a customer instead of

**Comment by anhmht** [comment]
Need to validate the search input before searching.
![screencapture-localhost-3000-search-2019-03-18-20_09_43](https://user-images.githubusercontent.com/38060950/54532213-cededc00-49b9-11e9-9322-93adc3ef3fe5.png)
Increase the width of the customer creation form and change the label of form input to make form prettier
![screencapture-localhost-3000-search-2019-03-18-20_10_31](https://user-images.githubusercontent.com/38060950/54532257-ec13aa80-49b9-11e9-8daf-46cf42830d9e.png)
Something went wrong when search tracking
```
static searchTracking = (trackingId) => {
    const tracking = Trackings.findOne({
      trackingNumber: trackingId,
    }, {
      fields: {
        _id: 1,
        trackingNumber: 1,
        status: 1,
        userId: 1,
        flightId: 1
      },
    });
    if (!tracking) return null;
    let customer = null;
    if (tracking.userId) {
      customer = CustomerWorker.findCustomerByUniqueId(tracking.userId);
    }
    let flight = null;
    if (tracking.flightId) {
      flight = Flights.findOne({
        _id: tracking.flightId
      });
    }
    const result = {
      tracking,
      customer,
      flight
    };
    return result;
  }
```

**Comment by anhmht** [comment]
![screencapture-localhost-3000-search-2019-03-18-20_47_38](https://user-images.githubusercontent.com/38060950/54534540-27fd3e80-49bf-11e9-86a8-0100de3c9252.png)
Added 2 buttons `Chọn khách hàng` and `Cập nhật trạng thái` at the bottom. Can u explain each function in detail ?
