### ISSUE TITLE
Warning on console log in FlightPage

### ISSUE THREAD

**Issue by hoadinh2010** [hoadinh2010/Vietexpress#61]
![image](https://user-images.githubusercontent.com/48083610/54594086-862f2d80-4a62-11e9-89b1-f3fb846499d7.png)

**Comment by NguyenMinhh** [comment]
As https://github.com/hoadinh2010/Vietexpress/issues/55, When click on ```Chuyến bay``` will show list of flight. Can I remove this router. Function add new fight just show in modal when user lick button ``` Thêm Chuyến Bay ``` in header. How do you think ?

**Comment by hoadinh2010** [comment]
@NguyenMinhh  Yes, this is my idea. The progress of adding tracking ID is:
Click `Thêm CHuyến bay` on the top bar or on the list flight page -> Add flight modal appear -> After create flight -> move to your add Tracking page -> after finish adding tracking -> Move back to list flight page
