### ISSUE TITLE
Enhance the checking process

### ISSUE THREAD

**Issue by hoadinh2010** [hoadinh2010/Vietexpress#67]
- [x]  In the list of Flights, we will have a Kiểm tra button at the end of each On board flights.
- [x]  After created a new flight -> move to the add tracking to flight  -> Done -> move back to the flight list. 
*Notes*: The adding Tracking to flight component will be used global. Much use carefully
- [x]  If we have a new tracking on the flight, show a modal to notice the user  and a dropdown to choose customer which is exactly the same with the dropdown khách hàng  on the add tracking to Flight page
- [x]  After finishing the check progress -> Click done -> Check if in the checked flight still have the trackings are not checked -> show a message to notice user and show the list of uncheck tracking 
- [x] Add a new attribute to the Tracking collection : `timeline`. Timeline is an object:
` 
{
ON_BOARD: time,
VN_DELIVERIED: time
}
`
each <key, value> of timeline will be the time change to the status. The key will be the enum of the status. Change the method `updateStatus` to update the timeline, too
- [x] When finish checking process, set the flight status to `DONE`  and back to the flight list.
- [x] In the flight list, if flight status is `Done` -> have a button `Tạo hóa đơn` at the end of flight 
- [x] If the flight status is `Arrived` -> have a button `Kiểm tra` at the end of flight 
- [x] When click on the `Kiểm tra` button -> change status to `Checking`

**Comment by NguyenMinhh** [comment]
In this issues, just check tracking with condition ```trackingNumber``` and ```flightId```, not include ```userId``` ?

**Comment by dinhnguyentrunghoa** [comment]
Woa, good question! We need to check the user ID, too 

> In this issues, just check tracking with condition `trackingNumber` and `flightId`, not include `userId` ?

**Comment by NguyenMinhh** [comment]
understood, but when we have diffence between userId and user select, in this task, i just update tracking status, don't need to update userId ?

**Comment by NguyenMinhh** [comment]
```After finishing the check progress -> Click done -> Check if in the checked flight still have the trackings are not checked -> show a message to notice user and show the list of uncheck tracking```
```When finish checking process, set the flight status to DONE and back to the flight list.```

When still have tracking are not checked -> click done -> show notice -> after that, flight status still set to ```DONE``` or what's status in this case ?
