### ISSUE TITLE
Implement Create receipt form (UI only)

### ISSUE THREAD

**Issue by hoadinh2010** [hoadinh2010/Vietexpress#72]
- [x] This form will load data from a flight which is `Done`
- [x] Have a dropdown to choose customer which have the tracking on this flight
- [x] When choose a customer will show the `Thêm loại hàng` button
- [ ] Each time Click on above button -> A line have been inserted include: Mặt hàng dropdown, số lượng, Kg/cái dropdown. After inputed, we show 2 inputs more: `đơn giá` and `giá/phần trăm` which fetchs from `Don gia` collection.  we will compute the price and show at the right of this line.

**Comment by nguyenhuuhoanggiang** [comment]
Currency to use here must be USD. Decimal places: 2 (Ex: $5.00)

**Comment by nguyenhuuhoanggiang** [comment]
'Bảng Giá' contains types of goods below:
- Thường (Standard)
- Điện tử (Electronics)
- Mỹ phẩm (Cosmetics)
- Nước hoa (Perfume)
- Thực Phẩm chức Năng (Nutritional supplements)
- Phụ tùng xe (Vehicle/Bike parts)
