### ISSUE TITLE
Improve search tracking number function

### ISSUE THREAD

**Issue by nguyenhuuhoanggiang** [hoadinh2010/Vietexpress#99]
Allow LIKE search.
Consider to show a result list or to show suggestion as drop down list.

**Comment by hoadinh2010** [comment]
I suggest that 2 case:
- When the search returns only one item, show the detailed tracking like the already implemented page. 
- If the search returns more than one, show the list trackings, each tracking is a card (using Card component of the ant design )
![image](https://user-images.githubusercontent.com/48083610/54983470-85a51280-4fdf-11e9-8999-c231552b5712.png)
when click on the card will be moved to the detailed page like above

**Comment by nguyenhuuhoanggiang** [comment]
Input must be at least 4 numbers @anhmht

**Comment by hoadinh2010** [comment]
I think we should force user to click search or enter to search, too!
